# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

definitions:
  services:
    docker:
      memory: 2048 # Increasing Docker Memory Size to 2GB instead of defailt 1GB
  steps:
    # DEFINE Mirror to Github STEP
    - step: &github
        name: "Mirror to Github"
        script:
          - git push --mirror git@github.com:AlkemiNetwork/alkemi-earn-contracts.git

pipelines:
  branches:
    master:
      # Runs only on Master Branch
      - step: *github
