version: "3"
services:
  mythx-eth:
    image: nikolaik/python-nodejs:latest
    container_name: mythx-eth
    environment:
      - MYTHX_API_KEY=${MYTHX_API_KEY}
    volumes:
      - .:/usr/src/app:cached
    entrypoint: |
      bash -c "cd /usr/src/app
      pip3 install mythx-cli
      npm install
      mythx analyze ./contracts/RewardControl.sol ./contracts/MoneyMarketV12.sol ./contracts/RewardControlInterface.sol ./contracts/RewardControlStorage.sol ./contracts/ExponentialNoError.sol --solc-version 0.4.24 --mode standard
      tail -f /dev/null"