#!/bin/sh

set -eo pipefail

DIR=$(dirname $0)
PROJ_ROOT="$DIR/../.."

network="$1"
asset="$2"
interest_rate_model="$3"
update_alkemi_earn_verified=${4:-no_thanks}

if [ -z "$network" ]; then
	echo "usage: scripts/blockchain/update-interest-rate {network} {asset} {interest_rate_model} {update_alkemi_earn_verified (optional, defaults to no) }"
	echo ""
	echo "deploy a new interest rate contract ( if necessary ) and update the Alkemi Earn Verified ( if you pass a value for update_alkemi_earn_verified ) to use it for an an asset"
	exit 1
fi

NETWORK="$network" ASSET="$asset" INTEREST_RATE_MODEL="$interest_rate_model" UPDATE_ALKEMI_EARN_VERIFIED=$update_alkemi_earn_verified truffle exec --network="$network" "$DIR/../javascript/updateInterestRateModel.js"
