version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.9.0
      - image: trufflesuite/ganache-cli:v6.12.2
        command: ganache-cli --allowUnlimitedContractSize
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          name: Save NPM Package Cache
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test contracts
          command: npm run test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml

  lint:
    docker:
      - image: circleci/node:10.9.0
      - image: trufflesuite/ganache-cli:v6.1.8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/repo
      - run: npm run lint

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - lint
      - test
