#!/usr/bin/env sh

DIR=$(dirname $0)
PROJ_ROOT="$DIR/.."
TRUFFLE_DIR="$PROJ_ROOT/node_modules/truffle/build/cli.bundled.js"

# CarefulMathTest
# ErrorReporterTest
# ExponentialTest
"$TRUFFLE_DIR" test ./test/CarefulMathTest.sol ./test/ErrorReporterTest.sol ./test/ExponentialTest.sol ./test/AssertHelpers.sol --network development $@

## SafeTokenNonStandardTest
## SafeTokenTest
#"$TRUFFLE_DIR" test ./test/SafeTokenNonStandardTest.sol ./test/SafeTokenTest.sol ./test/AssertHelpers.sol ./test/EIP20NonStandardReturnHarness.sol ./test/EIP20Harness.sol ./test/AddressGenerator.sol --network development $@
#
## StableCoinInterestRateModelTest
## StandardInterestRateModelTest
#"$TRUFFLE_DIR" test ./test/StableCoinInterestRateModelTest.js ./test/StandardInterestRateModelTest.js ./test/AssertHelpers.sol ./test/MathHelpers.sol --network development $@
#
## MoneyMarketTest_AddCollateralMarket
## MoneyMarketTest_AssetPrices
## MoneyMarketTest_Basic
## MoneyMarketTest_Borrow
## MoneyMarketTest_CalculateAccountLiquidity
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_AddCollateralMarket.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketTest_AssetPrices.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketTest_Basic.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketTest_Borrow.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketTest_CalculateAccountLiquidity.sol ./test/MoneyMarket/MoneyMarketTest_CalculateAccountLiquidity2.sol ./test/MoneyMarket/MoneyMarketTest_CalculateAccountLiquidity3.sol ./test/MoneyMarket/MoneyMarketTest_CalculateAccountLiquidity4.sol ./test/MoneyMarket/MoneyMarketTest_CalculateAccountLiquidity5.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#
## MoneyMarketTest_CalculateAccountValues
## MoneyMarketTest_CalculateAmountSeize
## MoneyMarketTest_CalculateAmountSeize2
## MoneyMarketTest_CalculateBorrowAmountWithFee
## MoneyMarketTest_CalculateBalance
## MoneyMarketTest_CalculateDiscountedBorrowDenominatedCollateral
## MoneyMarketTest_CalculateDiscountedBorrowDenominatedCollateral2
## MoneyMarketTest_CalculateDiscountedRepayToEvenAmount
## MoneyMarketTest_CalculateDiscountedRepayToEvenAmount2
## MoneyMarketTest_CalculateInterestIndex
## MoneyMarketTest_CalculateInterestIndex2
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_CalculateAccountValues.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketTest_CalculateAmountSeize.sol ./test/MoneyMarket/MoneyMarketTest_CalculateAmountSeize2.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketTest_CalculateBorrowAmountWithFee.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketTest_CalculateBalance.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketTest_CalculateDiscountedBorrowDenominatedCollateral.sol ./test/MoneyMarket/MoneyMarketTest_CalculateDiscountedBorrowDenominatedCollateral2.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketTest_CalculateDiscountedRepayToEvenAmount.sol ./test/MoneyMarket/MoneyMarketTest_CalculateDiscountedRepayToEvenAmount2.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketTest_CalculateInterestIndex.sol ./test/MoneyMarket/MoneyMarketTest_CalculateInterestIndex2.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#
## MoneyMarketTest_GetAssetAmountForValue
## MoneyMarketTest_GetPriceForAssetAmount
## MoneyMarketTest_GetPriceForAssetAmountMulCollatRatio
## MoneyMarketTest_Oracle
## MoneyMarketTest_Oracle2
## MoneyMarketTest_SetMarketInterestRateModel
## MoneyMarketTest_SetRiskParameters
## MoneyMarketTest_SetRiskParameters2
## MoneyMarketTest_SetRiskParameters3
## MoneyMarketTest_SetRiskParameters4
## MoneyMarketTest_SetPendingAdmin
## MoneyMarketTest_SetOriginationFee
## MoneyMarketTest_Supply
## MoneyMarketTest_Supply_NonStandard
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_GetAssetAmountForValue.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_GetPriceForAssetAmount.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_GetPriceForAssetAmountMulCollatRatio.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_Oracle.sol ./test/MoneyMarket/MoneyMarketTest_Oracle2.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_SetMarketInterestRateModel.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_SetRiskParameters.sol ./test/MoneyMarket/MoneyMarketTest_SetRiskParameters2.sol ./test/MoneyMarket/MoneyMarketTest_SetRiskParameters3.sol ./test/MoneyMarket/MoneyMarketTest_SetRiskParameters4.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_SetPendingAdmin.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_SetOriginationFee.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_Supply.sol ./test/MoneyMarket/MoneyMarketTest_Supply_NonStandard.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#
## MoneyMarketTest_RepayBorrow
## MoneyMarketTest_SupportMarket
## MoneyMarketTest_SupportMarket2
## MoneyMarketTest_SupportMarket3
## MoneyMarketTest_SupportMarket4
## MoneyMarketTest_SuspendMarket
## MoneyMarketTest_Withdraw
## MoneyMarketTest_WithdrawEquity
## MoneyMarketTest_WithdrawEquity2
## MoneyMarketTest_WithdrawEquity3
## MoneyMarketTest_WithdrawEquity4
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_RepayBorrow.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_SupportMarket.sol ./test/MoneyMarket/MoneyMarketTest_SupportMarket2.sol ./test/MoneyMarket/MoneyMarketTest_SupportMarket3.sol ./test/MoneyMarket/MoneyMarketTest_SupportMarket4.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_SuspendMarket.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_Withdraw.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarket/MoneyMarketTest_WithdrawEquity.sol ./test/MoneyMarket/MoneyMarketTest_WithdrawEquity2.sol ./test/MoneyMarket/MoneyMarketTest_WithdrawEquity4.sol ./test/MoneyMarket/MoneyMarketTest_WithdrawEquity3.sol ./test/AddressGenerator.sol ./test/AssertHelpers.sol ./test/MathHelpers.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardReturnHarness.sol ./test/MoneyMarket/MoneyMarketTest.sol ./test/MoneyMarket/MoneyMarketNonStandardTest.sol ./test/MoneyMarket/MoneyMarketWithPriceTest.sol ./test/MoneyMarketLightHarness.sol --network development $@
#
## ErrorReporterTest
## MoneyMarketGasHarness
## MoneyMarketHarness
#"$TRUFFLE_DIR" test ./test/ErrorReporterHarness.sol ./test/ErrorReporterHarnessTest.js ./test/ErrorReporter.js ./test/PriceOracleHarness.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardThrowHarness.sol ./test/InterestRateModel/SimpleInterestRateModel.sol ./test/InterestRateModel/FailableInterestRateModel.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarketGasHarness.sol ./test/MoneyMarketGasHarnessTest.js ./test/ErrorReporter.js ./test/PriceOracleHarness.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardThrowHarness.sol ./test/InterestRateModel/SimpleInterestRateModel.sol ./test/InterestRateModel/FailableInterestRateModel.sol --network development $@
#"$TRUFFLE_DIR" test ./test/MoneyMarketHarness.sol ./test/MoneyMarketHarnessTest.js ./test/ErrorReporter.js ./test/PriceOracleHarness.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardThrowHarness.sol ./test/InterestRateModel/SimpleInterestRateModel.sol ./test/InterestRateModel/FailableInterestRateModel.sol --network development $@
#
## SafeTokenHarness
## Scenarios
## MoneyMarket
#"$TRUFFLE_DIR" test ./test/MoneyMarketTest.js ./test/SafeTokenHarness.sol ./test/SafeTokenHarnessTest.js ./test/Scenario.js ./test/ErrorReporter.js ./test/PriceOracleHarness.sol ./test/EIP20Harness.sol ./test/EIP20NonCompliantHarness.sol ./test/MoneyMarketScenario.sol ./test/InterestRateModel/AlwaysFailInterestRateModel.sol ./test/InterestRateModel/FixedInterestRateModel.sol ./test/Tokens/FaucetToken.sol ./test/Tokens/FaucetNonStandardToken.sol --network development $@
#
## TestKYC
#"$TRUFFLE_DIR" test ./test/testKYC.js --network development $@
