#!/usr/bin/env sh

DIR=$(dirname $0)
PROJ_ROOT="$DIR/.."
TRUFFLE_DIR="$PROJ_ROOT/node_modules/truffle/build/cli.bundled.js"
"$TRUFFLE_DIR" test ./test/AlkemiEarnVerifiedHarness.sol ./test/AlkemiEarnVerifiedHarnessTest.js ./test/ErrorReporter.js ./test/PriceOracleHarness.sol ./test/EIP20Harness.sol ./test/EIP20NonStandardThrowHarness.sol ./test/InterestRateModel/SimpleInterestRateModel.sol ./test/InterestRateModel/FailableInterestRateModel.sol --network development $@
